### ISSUE TITLE
[Q] Ninjhax and Release link.

### ISSUE THREAD

**Issue by lavanoid** [Lectem/SDBrowser#1]
Hi, found this repo and it looked interesting. Unfortunately, I can't compile the code and was wondering if there is a link to a pre-compiled binary... Also, is there Ninjhax support? The README.md doesn't state.

Thanks!

**Comment by Lectem** [comment]
Hi,
at the moment it can only display a directory, I uploaded it only as an example for ctrulibs user.
If I find the time I might do it for real, but I have other projects to do atm.
I just tried to compile it, and it works fine with lastest devkitpro + ctrulib
I suppose the binary won't be useful since as I said, it only lists the content of a directory

**Comment by lavanoid** [comment]
Oh, ok. Well, it sure would be awesome if you do get the time to do this for real, no one else has made a file manager (as far as I am aware of) for the 3DS.

Thanks!

**Comment by Lectem** [comment]
Actually it was in my plan to do some well featured browser, but I'm focusing on writing a hardware accelerated GUI library first, so that I'll be able to use it for the browser and other projects

**Comment by Lectem** [comment]
Actually it was in my plan to do some well featured browser, but I'm focusing on writing a hardware accelerated GUI library first, so that I'll be able to use it for the browser and other projects
